### ISSUE TITLE
Open Source Software Suggestions

### ISSUE THREAD

**Issue by TheWizardOfOsmium** [mitre/mitre.github.io#17]
Your Github said that this project is looking for suggestions for software to have GRAS, so I would like to submit the following. I develop software on a classified network, and I am having a difficult time getting these the okay.

Electron (http://electron.atom.io/apps/)
Atom (https://atom.io/)

**Comment by sbowman-mitre** [comment]
The GRAS page has been removed as of #20 . It seemed best to not take on the maintenance burden of such a page. Sorry for the slow response, @TheWizardOfOsmium .
