### ISSUE TITLE
Software Not Mentioned in Generally Recognized As Safe List

### ISSUE THREAD

**Issue by lneely** [mitre/mitre.github.io#20]
If the page at http://mitre.github.io/gras.html is considered the authoritative list of MITRE FOSS "Generally Recognized As Safe", then it should at least include the BSD distributions. The 2003 MITRE publication MP02W0000101 (cf., http://www.terrybollinger.com/dodfoss/dodfoss_html/index.html#recommendations), which makes an initial recommendation for a GRAS list for FOSS, suggests the following criteria:  "(a) commercially supported, (b) widely used, and (c) have proven track records of security and reliability—e.g., as measured by speed of closures of CERT reports in comparison to closed-source alternatives."  The BSD base systems meet at least two of these three criteria, so they should be included.  OpenBSD, NetBSD, and FreeBSD are also named specifically by the report.

Other software recommended for inclusion from the report:   Samba, Perl, GNAT, XFree86 (X.org), OpenSSH, bind, and sendmail.

**Comment by gtback** [comment]
I think it may be better to just remove that page. The maintenance burden would be pretty high, and it will only lead to more questions about why certain projects were included and some were not.

**Comment by gtback** [comment]
To be clear, I'm not opposed to the idea of the list, but it would probably be better served in its own repository, maintained by others who are focused on measuring what is considered "safe" open source software, and not in this repository.

**Comment by sbowman-mitre** [comment]
Yup, I agree with this approach. Thanks for cleaning it up Greg and thanks to @lneely for bumping us on this.
